---
title: "Math Department Data Analysis"
author: "Cameron Mitchell"
date: "23 Sep 2020"
output: html_notebook
---

The intention of this anaylsis is to try to determine how many students will be in MA132 (Calculus II) in the upcoming semester.


# Load packages
```{r}
library(tidyverse)
library(janitor)
library(readxl)
library(skimr)
library(summarytools)
```


# Read the data
```{r}
dfa = read_excel("~/DS241/CU_ACAD_DEPT_ENRL.xlsx") %>%
clean_names()
```



# Summary of data
```{r}
#skim(dfa)
# c = dfa %>% group_by(subject)
# skim(c)
# dfa %>% dfSummary()
```


# Tidy data
```{r}
dfb = dfa %>%
  separate(col = term2, into = c("semester","year"), sep = " ")
```


# Cleaning the data. 
```{r}
dfc = dfb %>%
  select(-c(acad_org,current_status,instructor,course_id)) %>%
  filter(subject == "MA", catalog == "131"|catalog == "132") %>%
  filter(component == "LEC") %>%
  unique() %>%
  group_by(title, semester, year) 

# df = dfc %>%
#   filter(tot_enrl_overall = sum(tot_enrlcase_when(catalog == "131"))

  summarise(dfc,
            tot_enrl = sum(tot_enrl))
```